export const moodThemes = {
  happy: {
    bg: 'bg-gradient-to-br from-amber-50 via-yellow-100 to-orange-200',
    text: 'text-slate-800',
    msgBgOwn: 'bg-amber-500',
    msgTextOwn: 'text-white',
    msgBgReceiver: 'bg-amber-400',
    msgTextReceiver: 'text-amber-950',
    accent: 'bg-amber-600',
    buttonHover: 'hover:bg-amber-400',
    shadow: 'shadow-amber-200',
  },
  calm: {
    bg: 'bg-gradient-to-br from-sky-50 via-blue-100 to-cyan-200',
    text: 'text-slate-800',
    msgBgOwn: 'bg-cyan-600',
    msgTextOwn: 'text-white',
    msgBgReceiver: 'bg-cyan-400',
    msgTextReceiver: 'text-cyan-950',
    accent: 'bg-cyan-700',
    buttonHover: 'hover:bg-cyan-500',
    shadow: 'shadow-cyan-200',
  },
  romantic: {
    bg: 'bg-gradient-to-br from-rose-50 via-pink-100 to-fuchsia-200',
    text: 'text-slate-800',
    msgBgOwn: 'bg-rose-500',
    msgTextOwn: 'text-white',
    msgBgReceiver: 'bg-rose-400',
    msgTextReceiver: 'text-rose-950',
    accent: 'bg-rose-600',
    buttonHover: 'hover:bg-rose-400',
    shadow: 'shadow-rose-200',
  },
  dark: {
    bg: 'bg-gradient-to-br from-zinc-900 via-slate-800 to-zinc-800',
    text: 'text-slate-700',
    msgBgOwn: 'bg-zinc-700',
    msgTextOwn: 'text-zinc-100',
    msgBgReceiver: 'bg-zinc-400',
    msgTextReceiver: 'text-zinc-150',
    accent: 'bg-indigo-600',
    buttonHover: 'hover:bg-indigo-500',
    shadow: 'shadow-zinc-900',
  },
  energetic: {
    bg: 'bg-gradient-to-br from-red-50 via-orange-100 to-red-200',
    text: 'text-slate-800',
    msgBgOwn: 'bg-red-500',
    msgTextOwn: 'text-white',
    msgBgReceiver: 'bg-red-400',
    msgTextReceiver: 'text-red-950',
    accent: 'bg-red-600',
    buttonHover: 'hover:bg-red-400',
    shadow: 'shadow-red-200',
  },
  professional: {
    bg: 'bg-gradient-to-br from-slate-50 via-slate-100 to-blue-100',
    text: 'text-slate-800',
    msgBgOwn: 'bg-blue-600',
    msgTextOwn: 'text-white',
    msgBgReceiver: 'bg-blue-400',
    msgTextReceiver: 'text-blue-950',
    accent: 'bg-blue-700',
    buttonHover: 'hover:bg-blue-500',
    shadow: 'shadow-blue-200',
  },
  serene: {
    bg: 'bg-gradient-to-br from-emerald-50 via-teal-100 to-green-200',
    text: 'text-slate-800',
    msgBgOwn: 'bg-emerald-600',
    msgTextOwn: 'text-white',
    msgBgReceiver: 'bg-emerald-400',
    msgTextReceiver: 'text-emerald-950',
    accent: 'bg-emerald-700',
    buttonHover: 'hover:bg-emerald-500',
    shadow: 'shadow-emerald-200',
  },
  modern: {
    bg: 'bg-gradient-to-br from-violet-50 via-purple-100 to-indigo-200',
    text: 'text-slate-800',
    msgBgOwn: 'bg-violet-600',
    msgTextOwn: 'text-white',
    msgBgReceiver: 'bg-violet-400',
    msgTextReceiver: 'text-violet-950',
    accent: 'bg-violet-700',
    buttonHover: 'hover:bg-violet-500',
    shadow: 'shadow-violet-200',
  },
  default: {
    bg: 'bg-gradient-to-br from-gray-50 via-slate-100 to-gray-200',
    text: 'text-slate-800',
    msgBgOwn: 'bg-slate-500',
    msgTextOwn: 'text-white',
    msgBgReceiver: 'bg-slate-400',
    msgTextReceiver: 'text-slate-950',
    accent: 'bg-slate-600',
    buttonHover: 'hover:bg-slate-400',
    shadow: 'shadow-slate-200',
  },
};
