export const moodThemes = {
  happy: {
    bg: 'bg-gradient-to-br from-amber-100 via-yellow-200 to-orange-300',
    text: 'text-slate-800',
    msgBgOwn: 'bg-amber-500',
    msgTextOwn: 'text-white',
    msgBgReceiver: 'bg-amber-400',
    msgTextReceiver: 'text-amber-950',
    accent: 'bg-amber-400',
    buttonHover: 'hover:bg-amber-400',
    shadow: 'shadow-amber-200',
  },
  calm: {
    bg: 'bg-gradient-to-br from-sky-100 via-blue-200 to-cyan-300',
    text: 'text-slate-800',
    msgBgOwn: 'bg-cyan-600',
    msgTextOwn: 'text-white',
    msgBgReceiver: 'bg-cyan-400',
    msgTextReceiver: 'text-cyan-950',
    accent: 'bg-cyan-400',
    buttonHover: 'hover:bg-cyan-500',
    shadow: 'shadow-cyan-200',
  },
  romantic: {
    bg: 'bg-gradient-to-br from-rose-100 via-pink-200 to-fuchsia-300',
    text: 'text-slate-800',
    msgBgOwn: 'bg-rose-400',
    msgTextOwn: 'text-white',
    msgBgReceiver: 'bg-rose-300',
    msgTextReceiver: 'text-rose-950',
    accent: 'bg-rose-400',
    buttonHover: 'hover:bg-rose-400',
    shadow: 'shadow-rose-200',
  },
  dark: {
    bg: 'bg-gradient-to-br from-zinc-200 via-slate-300 to-zinc-400',
    text: 'text-slate-700',
    msgBgOwn: 'bg-zinc-700',
    msgTextOwn: 'text-zinc-100',
    msgBgReceiver: 'bg-zinc-400',
    msgTextReceiver: 'text-zinc-150',
    accent: 'bg-indigo-400',
    buttonHover: 'hover:bg-indigo-500',
    shadow: 'shadow-zinc-900',
  },
  energetic: {
    bg: 'bg-gradient-to-br from-red-100 via-orange-200 to-red-300',
    text: 'text-slate-800',
    msgBgOwn: 'bg-red-500',
    msgTextOwn: 'text-white',
    msgBgReceiver: 'bg-red-400',
    msgTextReceiver: 'text-red-950',
    accent: 'bg-red-400',
    buttonHover: 'hover:bg-red-400',
    shadow: 'shadow-red-200',
  },
  professional: {
    bg: 'bg-gradient-to-br from-slate-100 via-slate-200 to-blue-300',
    text: 'text-slate-800',
    msgBgOwn: 'bg-blue-600',
    msgTextOwn: 'text-white',
    msgBgReceiver: 'bg-blue-400',
    msgTextReceiver: 'text-blue-950',
    accent: 'bg-blue-400',
    buttonHover: 'hover:bg-blue-500',
    shadow: 'shadow-blue-200',
  },
  default: {
    bg: 'bg-gradient-to-br from-gray-100 via-slate-200 to-gray-200',
    text: 'text-slate-800',
    msgBgOwn: 'bg-slate-500',
    msgTextOwn: 'text-white',
    msgBgReceiver: 'bg-slate-400',
    msgTextReceiver: 'text-slate-950',
    accent: 'bg-slate-400',
    buttonHover: 'hover:bg-slate-400',
    shadow: 'shadow-slate-200',
  },
};
